let varUno = 10;
let varDos = 30;
console.log("varUno es " + varUno);
console.log("varDos es " + varDos);
let aux;
aux = varUno;
varUno = varDos;
varDos = aux;
console.log("varUno es " + varUno);
console.log("varDos es " + varDos);
